°[project]
name = "synapseplan_backend"
version = "0.1.0"
description = "FastAPI backend for SynapsePlan"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "SQLAlchemy",
    "psycopg2-binary",
    "alembic",
    "pydantic-settings",
    "passlib[bcrypt]",
    "bcrypt==3.2.0",
    "python-jose[cryptography]",
    "python-multipart",
    "loguru",
    "APScheduler",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["crud", "models", "routers", "schemas", "services", "utils"]°"(895d416ae94c3d3f1d10e837bfe2ecc0bfb695382Jfile:///c:/Users/Admin/Documents/Coding/SynapsePlan/backend/pyproject.toml:3file:///c:/Users/Admin/Documents/Coding/SynapsePlan